# Generated by Django 5.2.17 on 2026-09-21 13:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        ('obligations', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule', models.CharField(db_index=True, max_length=60)),
                ('points', models.PositiveIntegerField(default=0)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('title', models.CharField(max_length=300)),
                ('explanation', models.TextField()),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_findings', to='contracts.contract')),
                ('obligation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_findings', to='obligations.obligation')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_findings', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-points', '-created_at'],
                'indexes': [models.Index(fields=['workspace', '-points'], name='risks_riskf_workspa_d8486a_idx'), models.Index(fields=['contract', '-points'], name='risks_riskf_contrac_cbcee5_idx'), models.Index(fields=['workspace', 'rule'], name='risks_riskf_workspa_9adac0_idx')],
            },
        ),
    ]
