# Generated by Django 5.2.17 on 2026-09-21 13:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        ('obligations', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('kind', models.CharField(choices=[('FIXED', 'Fixed date'), ('RELATIVE', 'Relative to anchor'), ('RENEWAL', 'Renewal'), ('RENEWAL_NOTICE', 'Renewal notice'), ('EXPIRY', 'Contract expiry'), ('RECURRING', 'Recurring instance')], db_index=True, default='FIXED', max_length=16)),
                ('due_date', models.DateField(db_index=True)),
                ('anchor_date', models.DateField(blank=True, help_text='Anchor the offset was computed from.', null=True)),
                ('offset_days', models.IntegerField(blank=True, null=True)),
                ('business_days', models.BooleanField(default=False)),
                ('rule', models.CharField(blank=True, help_text="Human-readable derivation, e.g. '60 days before renewal 2026-12-15'.", max_length=500)),
                ('completed', models.BooleanField(db_index=True, default=False)),
                ('waived', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='contracts.contract')),
                ('obligation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='obligations.obligation')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['due_date', 'created_at'],
                'indexes': [models.Index(fields=['workspace', 'due_date'], name='deadlines_d_workspa_02cb4d_idx'), models.Index(fields=['contract', 'due_date'], name='deadlines_d_contrac_e80a07_idx'), models.Index(fields=['obligation', 'due_date'], name='deadlines_d_obligat_9b1536_idx')],
            },
        ),
    ]
