# Generated by Django 5.2.17 on 2026-09-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='file',
            field=models.FileField(max_length=500, upload_to='evidence/%Y/%m/'),
        ),
    ]
