# Generated by Django 5.2.17 on 2026-09-21 12:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        ('documents', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clause',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_number', models.PositiveIntegerField(db_index=True, default=1)),
                ('heading', models.CharField(blank=True, max_length=300)),
                ('text', models.TextField()),
                ('clause_type', models.CharField(choices=[('DEFINITIONS', 'Definitions'), ('PAYMENT', 'Payment'), ('RENEWAL', 'Renewal'), ('TERMINATION', 'Termination'), ('INSURANCE', 'Insurance'), ('CONFIDENTIALITY', 'Confidentiality'), ('SECURITY', 'Security'), ('COMPLIANCE', 'Compliance'), ('SLA', 'SLA'), ('REPORTING', 'Reporting'), ('AUDIT', 'Audit'), ('LIABILITY', 'Liability'), ('INDEMNIFICATION', 'Indemnification'), ('NOTICE', 'Notice'), ('DELIVERY', 'Delivery'), ('GENERAL', 'General')], db_index=True, default='GENERAL', max_length=20)),
                ('start_offset', models.PositiveIntegerField(default=0)),
                ('end_offset', models.PositiveIntegerField(default=0)),
                ('confidence', models.FloatField(default=0.5)),
                ('extraction_method', models.CharField(choices=[('RULE', 'Rule'), ('LLM', 'LLM'), ('HYBRID', 'Hybrid')], default='RULE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='contracts.contract')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='documents.document')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clauses', to='documents.documentpage')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['document_id', 'page_number', 'start_offset'],
                'indexes': [models.Index(fields=['workspace', 'clause_type'], name='clauses_cla_workspa_fcbe66_idx'), models.Index(fields=['contract', 'clause_type'], name='clauses_cla_contrac_2197fd_idx'), models.Index(fields=['document', 'page_number'], name='clauses_cla_documen_bf5ad0_idx')],
            },
        ),
    ]
