# Generated by Django 5.2.17 on 2026-09-21 12:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clauses', '0001_initial'),
        ('contracts', '0001_initial'),
        ('documents', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Obligation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_number', models.PositiveIntegerField(default=1)),
                ('source_text', models.TextField(help_text='Exact evidence text backing this obligation.')),
                ('title', models.CharField(max_length=300)),
                ('obligation_type', models.CharField(choices=[('INSURANCE', 'Insurance'), ('PAYMENT', 'Payment'), ('REPORTING', 'Reporting'), ('RENEWAL_NOTICE', 'Renewal notice'), ('TERMINATION_NOTICE', 'Termination notice'), ('COMPLIANCE', 'Compliance'), ('SLA', 'SLA'), ('CONFIDENTIALITY', 'Confidentiality'), ('SECURITY', 'Security'), ('AUDIT', 'Audit'), ('DELIVERY', 'Delivery'), ('GENERAL', 'General')], db_index=True, default='GENERAL', max_length=20)),
                ('actor', models.CharField(blank=True, help_text='Party bound (e.g. Vendor).', max_length=120)),
                ('action', models.CharField(blank=True, max_length=300)),
                ('requirement', models.CharField(blank=True, max_length=500)),
                ('frequency', models.CharField(choices=[('ONE_TIME', 'One time'), ('CONTINUOUS', 'Continuous'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('SEMI_ANNUAL', 'Semi-annual'), ('ANNUAL', 'Annual'), ('CUSTOM', 'Custom')], default='ONE_TIME', max_length=16)),
                ('evidence_required', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('NEEDS_REVIEW', 'Needs review'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected'), ('ACTIVE', 'Active'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('WAIVED', 'Waived')], db_index=True, default='NEEDS_REVIEW', max_length=16)),
                ('confidence', models.FloatField(default=0.5)),
                ('extraction_method', models.CharField(choices=[('RULE', 'Rule'), ('LLM', 'LLM'), ('HYBRID', 'Hybrid')], default='RULE', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clause', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obligations', to='clauses.clause')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligations', to='contracts.contract')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obligations', to='documents.document')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_obligations', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_obligations', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligations', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', 'status'], name='obligations_workspa_76873d_idx'), models.Index(fields=['contract', 'status'], name='obligations_contrac_6000d5_idx'), models.Index(fields=['workspace', 'obligation_type'], name='obligations_workspa_882927_idx'), models.Index(fields=['owner', 'status'], name='obligations_owner_i_42bba2_idx')],
            },
        ),
    ]
