# Generated by Django 5.2.17 on 2026-09-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obligations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='obligation',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='obligation',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], db_index=True, default='MEDIUM', max_length=10),
        ),
    ]
